asu_userpicker.settings:
  type: mapping
  label: Settings
  mapping:
    asu_userpicker_solr_query_url:
      type: string
    asu_userpicker_referenceable_roles:
      type: mapping
    asu_userpicker_search_blocked_status:
      type: boolean
